apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: jenkins
spec:
  selector:
    istio: gateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - jenkins.local.domain
