apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: kiali-server-vs
spec:
  hosts:
    - kiali.local.domain
  gateways:
    - kiali-server
  http:
    - name: kiali-server
      match:
        - uri:
            prefix: "/"
      route:
        - destination:
            host: kiali
            port:
              number: 20001
