image:
  tag: "latest"
env:
  - name: ENVIRONMENT
    value: blue

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3

istio:
  enabled: true

hosts:
  - datereporter.local.domain

canary:
  enabled: true
