{{- if .Values.canary.enabled }}
apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: {{ include "datereporter.fullname" . }}
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "datereporter.fullname" . }}
  # the maximum time in seconds for the canary deployment
  # to make progress before rollback (default 600s)
  progressDeadlineSeconds: 600
  # HPA reference (optional)
  autoscalerRef:
    apiVersion: autoscaling/v2beta2
    kind: HorizontalPodAutoscaler
    name: {{ include "datereporter.fullname" . }}
  service:
    port: 8080
    portDiscovery: true
    {{- if .Values.istio.enabled }}
    gateways:
      - {{ include "datereporter.fullname" . }}
    {{- with .Values.hosts }}
    hosts:
    {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- end }}
  analysis:
    # schedule interval (default 60s)
    interval: {{ .Values.canary.analysis.interval }}
    # max number of failed checks before rollback
    threshold: {{ .Values.canary.analysis.threshold }}
    # number of checks to run before rollback
    maxWeight: {{ .Values.canary.analysis.maxWeight }}
    # canary increment step
    # percentage (0-100)
    stepWeight: {{ .Values.canary.analysis.stepWeight }}
    # Prometheus checks based on 
    # http_request_duration_seconds histogram
    metrics:
      - name: request-success-rate
        # minimum req success rate (non 5xx responses)
        # percentage (0-100)
        thresholdRange:
          min: 99
        interval: 5m
{{- end }}
