{{- if .Values.istio.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: argocd-vs
spec:
  hosts:
    - argocd.local.domain
  gateways:
  - argocd
  http:
    - name: argocd
      match:
        - uri:
            prefix: "/"
      route:
        - destination:
            host: argocd-server
            port:
              number: 80
{{- end }}
