{{- if .Values.istio.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: vault-vs
spec:
  hosts:
    - vault.local.domain
  gateways:
  - vault
  http:
    - name: vault
      match:
        - uri:
            prefix: "/"
      route:
        - destination:
            host: vault-ui
            port:
              number: 8200
{{- end }}
