apiVersion: v1
kind: ConfigMap
metadata:
  name: datasource-prometheus
  labels:
    grafana_datasource: "1"
data:
  prometheus.yaml: |-
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      access: proxy
      url: http://prometheus-server.platform.svc.cluster.local
      isDefault: true
