{{- if .Values.istio.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: grafana-vs
spec:
  hosts:
    - grafana.local.domain
  gateways:
  - grafana
  http:
    - name: grafana
      match:
        - uri:
            prefix: "/"
      route:
        - destination:
            host: grafana
            port:
              number: 80
{{- end }}
